collections:
  spells:
    output: true
    permalink: /:collection/:name
  items:
    output: true
    permalink: /:collection/:name
  chapter:
    output: true
    permalink: "/compendien/:path"
  compendien:
    output: true
    permalink: /:collection/:name
  spezies:
    output: true
    permalink: /:collection/:name
  subspezies:
    output: false
  
permalink: /:categories/:year/:month/:day/:title
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: "default"
  - scope:
      path: "/api"
    values:
      layout: "none"
  - scope:
      path: ""
      type: "spells"
    values:
      layout: "spell"
  - scope:
      path: ""
      type: "compendien"
    values:
      layout: compendium
      toc: true
  - scope:
      path: ""
      type: "chapter"
    values:
      layout: chapter
      toc: true

toc:
  min_level: 2
  max_level: 3
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: toc-section
  sublist_class: toc-section-sub
  item_class: toc-entry
  item_prefix: toc-

plugins:
 - jekyll-sitemap
 - jekyll-toc

