backend:
  name: github
  repo: jane7353n0/Utopia # Path to your GitHub repository
  # optional, defaults to master
  branch: main

  # This line should *not* be indented
media_folder: "assets/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: compendium
    label: "Compendium"
    folder: "_compendien/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: chapter
    label: "Chapter"
    folder: "_chapter/"
    create: true
    slug: "{{compendium}}/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: Compendium
        name: compendium
        widget: relation
        collection: compendium
        search_fields: [title]
        value_field: title
        display_fields: [title]
      - { label: "Chapter", name: "chapter", widget: "number"}
      - { label: "Body", name: "body", widget: "markdown" }